const mongoose = require("mongoose");

const equipmentSchema = new mongoose.Schema({
  dolly: Number,
  comp: Number,
  panel: Number,
  library: Number,
  bin: Number,
  techBin: Number,
  trashBin: Number,
  tool: [String],
  makitaCount: Number,
  makita: [Number],
  ramp14: Number,
  ramp10: Number,
  ramp8: Number,
  ramp6: Number,
  platform: Number,
  steelPlate: Number,
  hoodLift: Number,
  safeJackCount: Number,
  safeJack: [String],
  palletJack: Number,
  skinnyJack: Number,
  jBar: Number,
  bigRed: Number,
  masonite4: Number,
  masonite8: Number,
  ductTape: Number,
  blutTape: Number,
  coroflex: String,
  carpetGuard: Boolean,
  broom: Boolean,
  allenSet: Boolean,
  bitBox: Boolean,
  socketSet: Boolean,
  foamAcknowledge: Boolean,
  foam1L: String,
  foam1S: String,
  foam2L: String,
  foam2S: String,
  white: String,
  carpetRiser: Number,
  rubberRiser: Number,
  other: String,
});

const Equipment = mongoose.model("Equipment", equipmentSchema);

module.exports = Equipment;
