const mongoose = require("mongoose");

const moveSchema = new mongoose.Schema({
  date: Date,
  startTime: String,
  estimate: String,
  origin: {
    company: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },
    contact: { type: mongoose.Schema.Types.ObjectId, ref: "Contact" },
    altContact: { type: mongoose.Schema.Types.ObjectId, ref: "Contact" },
    additional: String,
  },
  destination: {
    company: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },
    contact: { type: mongoose.Schema.Types.ObjectId, ref: "Contact" },
    altContact: { type: mongoose.Schema.Types.ObjectId, ref: "Contact" },
    additional: String,
  },
  noCrewCab: Boolean,
  tailgate: Boolean,
  truck100: Boolean,
  openBack: Boolean,
  stairs: Boolean,
  tooltime: Boolean,
  crewSize: Number,
  trucks: [Number],
  vans: [Number],
  supervisors: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  drivers: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  helpers: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  techs: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  equipment: {
    dollies: Number,
    comps: Number,
    panels: Number,
    library: Number,
    bins: Number,
    teachBins: Number,
    trashBins: Number,
    tools: [String],
    makita: [Number],
    ramps: [Number],
    platform: Number,
    steelPlate: Number,
    hoodLift: Number,
    safeJacks: [String],
    palletJacks: Number,
    sknnyJack: Number,
    Jbar: Number,
    bigRed: Number,
    masonite: String,
    ductTape: Number,
    blutTape: Number,
    coroflex: Number,
    carpetGuard: Boolean,
    broom: Boolean,
    allenSet: Boolean,
    bitBox: Boolean,
    socketSet: Boolean,
    foam: [String],
    white: [String],
    carpetRiser: Number,
    rubberRiser: Number,
    other: String,
  },
  description: String,
  insurance: String,
  billTo: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },
  attention: String,
  holdForCrates: Boolean,
  salesMan: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  author: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  poNum: Number,
  projectNum: Number,
  references: String,
  groupBill: String,
  prePayment: String,
});

const Move = mongoose.model("Move", moveSchema);

module.exports = Move;
